### Create Risk Dataset

In [31]:
risk_df = X_test.copy()

risk_df['Actual_Risk'] = y_test.values

risk_df['Risk_Probability'] = risk_scores

### Risk Category

In [32]:
def classify_risk(prob):

    if prob < 0.30:
        return "Low Risk"

    elif prob < 0.70:
        return "Medium Risk"

    else:
        return "High Risk"

In [33]:
risk_df['Risk_Category'] = risk_df['Risk_Probability'].apply(classify_risk)

In [34]:
risk_df.head()

,Type,Days for shipment (scheduled),Benefit per order,Sales per customer,Category Id,Category Name,Customer City,Customer Country,Customer Fname,Customer Id,...,Product Price,Shipping Mode,Shipping_Pressure_Index,Delivery_Gap,Order_Complexity_Score,Express_Flag,Regional_Congestion,Actual_Risk,Risk_Probability,Risk_Category
69318,TRANSFER,4,-45.35,56.69,17,Cleats,Chicago,EE. UU.,Bryan,5002,...,59.99,Standard Class,0.2,2,59.99,0,0.543087,0,0.000440,Low Risk
84032,DEBIT,4,10.54,169.99,48,Water Sports,Brooklyn,EE. UU.,Mary,6012,...,199.99,Standard Class,0.2,0,199.99,0,0.558486,0,0.000011,Low Risk
160369,TRANSFER,4,11.31,113.09,18,Men's Footwear,Kent,EE. UU.,Mary,11589,...,129.99,Standard Class,0.2,-1,129.99,0,0.558486,0,0.000010,Low Risk
149768,TRANSFER,4,-17.76,92.96,46,Indoor/Outdoor Games,Caguas,Puerto Rico,Mary,10826,...,49.98,Standard Class,0.4,0,99.96,0,0.558486,0,0.000010,Low Risk
107905,PAYMENT,4,84.47,263.98,43,Camping & Hiking,Fullerton,EE. UU.,Edward,7790,...,299.98,Standard Class,0.2,1,299.98,0,0.547546,1,0.999982,High Risk

### KPI Dashboard Dataset

In [35]:
kpi_df = risk_df.copy()

##### Total Orders

In [36]:
total_orders = len(kpi_df)

print("Total Orders :", total_orders)

Total Orders : 36104

##### High Risk Orders

In [37]:
high_risk_orders = len(

    kpi_df[
        kpi_df['Risk_Category'] == 'High Risk'
    ]
)

print("High Risk Orders :", high_risk_orders)

High Risk Orders : 19796

##### Medium Risk Orders

In [38]:
medium_risk_orders = len(

    kpi_df[
        kpi_df['Risk_Category'] == 'Medium Risk'
    ]
)

print("Medium Risk Orders :", medium_risk_orders)

Medium Risk Orders : 0

##### Low Risk Orders

In [39]:
low_risk_orders = len(

    kpi_df[
        kpi_df['Risk_Category'] == 'Low Risk'
    ]
)

print("Low Risk Orders :", low_risk_orders)

Low Risk Orders : 16308

##### Average Risk Probability

In [40]:
avg_risk = round(

    kpi_df['Risk_Probability'].mean(),
    3
)

print("Average Risk :", avg_risk)

Average Risk : 0.548

### Region Risk Analysis Dataset

In [41]:
region_risk = (

    kpi_df
    .groupby('Order Region')
    ['Risk_Probability']
    .mean()
    .reset_index()
)

region_risk.head()

      Order Region  Risk_Probability
0           Canada          0.536838
1        Caribbean          0.525611
2   Central Africa          0.621012
3  Central America          0.536982
4     Central Asia          0.475413

### Shipping Mode Risk Analysis

In [42]:
mode_risk = (

    kpi_df
    .groupby('Shipping Mode')
    ['Risk_Probability']
    .mean()
    .reset_index()
)

mode_risk.head()

    Shipping Mode  Risk_Probability
0     First Class          0.954431
1        Same Day          0.457651
2    Second Class          0.767855
3  Standard Class          0.379658

### Customer Segment Risk

In [43]:
segment_risk = (

    kpi_df
    .groupby('Customer Segment')
    ['Risk_Probability']
    .mean()
    .reset_index()
)

segment_risk.head()

  Customer Segment  Risk_Probability
0         Consumer          0.548108
1        Corporate          0.544150
2      Home Office          0.556003

### Top High-Risk Orders

In [44]:
top_high_risk = (

    kpi_df
    .sort_values(
        by='Risk_Probability',
        ascending=False
    )
)

top_high_risk.head(20)

,Type,Days for shipment (scheduled),Benefit per order,Sales per customer,Category Id,Category Name,Customer City,Customer Country,Customer Fname,Customer Id,...,Product Price,Shipping Mode,Shipping_Pressure_Index,Delivery_Gap,Order_Complexity_Score,Express_Flag,Regional_Congestion,Actual_Risk,Risk_Probability,Risk_Category
39041,PAYMENT,2,150.87,327.98,45,Fishing,Cleveland,EE. UU.,Gregory,2802,...,399.98,Second Class,0.333333,2,399.98,0,0.547546,1,0.999989,High Risk
29947,DEBIT,2,11.64,290.98,43,Camping & Hiking,Tempe,EE. UU.,Ashley,2145,...,299.98,Second Class,0.333333,3,299.98,0,0.543087,1,0.999989,High Risk
145011,CASH,2,-21.93,169.98,9,Cardio Equipment,Caguas,Puerto Rico,Brenda,10490,...,99.99,Second Class,0.666667,3,199.98,0,0.552837,1,0.999989,High Risk
82973,DEBIT,2,74.38,212.50,24,Women's Apparel,Caguas,Puerto Rico,Michael,5936,...,50.00,Second Class,1.666667,2,250.00,0,0.547546,1,0.999989,High Risk
31068,PAYMENT,2,-25.23,56.07,41,Trade-In,Aurora,EE. UU.,Carolyn,2228,...,21.99,Second Class,1.000000,3,65.97,0,0.540441,1,0.999989,High Risk
140267,CASH,2,33.34,284.95,17,Cleats,Sylmar,EE. UU.,Sharon,10140,...,59.99,Second Class,1.666667,4,299.95,0,0.556633,1,0.999989,High Risk
53657,DEBIT,2,44.08,125.95,46,Indoor/Outdoor Games,Caguas,Puerto Rico,John,3877,...,49.98,Second Class,1.000000,3,149.94,0,0.562670,1,0.999989,High Risk
70575,DEBIT,2,18.20,181.95,29,Shop By Sport,Caguas,Puerto Rico,Janet,5085,...,39.99,Second Class,1.666667,3,199.95,0,0.558486,1,0.999989,High Risk
48951,PAYMENT,2,22.10,129.99,18,Men's Footwear,Aurora,EE. UU.,Amanda,3531,...,129.99,Second Class,0.333333,2,129.99,0,0.528409,1,0.999989,High Risk
4242,PAYMENT,2,14.60,33.19,29,Shop By Sport,Wayne,EE. UU.,Deborah,317,...,39.99,Second Class,0.333333,3,39.99,0,0.555299,1,0.999989,High Risk
4173,DEBIT,2,77.70,210.00,24,Women's Apparel,Houston,EE. UU.,Jack,312,...,50.00,Second Class,1.666667,4,250.00,0,0.547546,1,0.999989,High Risk
79761,CASH,2,-12.31,215.96,17,Cleats,Bakersfield,EE. UU.,Robert,5717,...,59.99,Second Class,1.333333,2,239.96,0,0.545173,1,0.999989,High Risk
27027,PAYMENT,2,91.13,185.98,9,Cardio Equipment,El Paso,EE. UU.,Mary,1937,...,99.99,Second Class,0.666667,2,199.98,0,0.528409,1,0.999989,High Risk
8425,DEBIT,2,95.99,239.98,43,Camping & Hiking,Caguas,Puerto Rico,Mary,612,...,299.98,Second Class,0.333333,2,299.98,0,0.552404,1,0.999989,High Risk
53005,CASH,2,108.85,226.76,17,Cleats,West Jordan,EE. UU.,Mary,3822,...,59.99,Second Class,1.333333,2,239.96,0,0.543845,1,0.999989,High Risk
160538,DEBIT,2,0.00,148.76,29,Shop By Sport,Caguas,Puerto Rico,Mary,11604,...,39.99,Second Class,1.333333,4,159.96,0,0.558486,1,0.999989,High Risk
100413,PAYMENT,2,35.25,74.99,9,Cardio Equipment,Brooklyn,EE. UU.,Mary,7218,...,99.99,Second Class,0.333333,3,99.99,0,0.552404,1,0.999989,High Risk
41658,DEBIT,2,114.83,395.98,45,Fishing,Caguas,Puerto Rico,Barbara,3006,...,399.98,Second Class,0.333333,2,399.98,0,0.530777,1,0.999989,High Risk
884,PAYMENT,2,102.18,217.41,46,Indoor/Outdoor Games,Caguas,Puerto Rico,Mary,66,...,49.98,Second Class,1.666667,2,249.90,0,0.543087,1,0.999989,High Risk
146744,DEBIT,2,19.89,48.50,24,Women's Apparel,Caguas,Puerto Rico,Nancy,10610,...,50.00,Second Class,0.333333,4,50.00,0,0.558486,1,0.999989,High Risk

### Saving Dashboard Dataset

In [45]:
kpi_df.to_csv(
    "risk_predictions.csv",
    index=False
)

print("Dashboard Dataset Saved")

Dashboard Dataset Saved